version = 0.1

[prod.deploy.parameters]
stack_name = "stand-backend-prod"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
region = "us-east-1"
